### PR TITLE
feat(script): Anti-Ban Features

### PR DESCRIPTION
**Pull request by suryadip2008**
New Anti-Ban Features added in the message_bomber.js script. Users can toggle it off or on.

### CODE REVIEW

**Comment by bocajthomas** [comment]
@suryadip2008 can you update the [SCRIPTLIST.md](https://github.com/suryadip2008/Scripts/blob/patch-1/SCRIPTLIST.md#message-bomber)

**Comment by suryadip2008** [comment]
> @suryadip2008 can you update the [SCRIPTLIST.md](https://github.com/suryadip2008/Scripts/blob/patch-1/SCRIPTLIST.md#message-bomber)

Please don't merge this yet, I will rollout one more commit to this script and bump the version to v3.5. (Some anti-ban features)

**Comment by bocajthomas** [comment]
Ready now?

**Comment by suryadip2008** [comment]
> Ready now?

A few minutes please.

**Pull request merged**
